### ISSUE TITLE
Igraph issue

### ISSUE THREAD

**Issue by Svenh98** [cytoscape/py2cytoscape#19]
Hello,

I recently discovered that if a user installs igraph, you will get a warning telling that igraph is now changed to jgraph. So py2cytoscape doesn't work then since it uses igraph.
When the import in util/util_igraph.py is changed to jgraph instead of igraph it works.

Kind regards,
Sven

**Comment by keiono** [comment]
@Svenh98 I never heard of this issue.  I can still use igraph.  jGraph is a java library which does not supported by this package.

**Comment by jorgeboucas** [comment]
using `python-igraph`
