### ISSUE TITLE
How does this library work?

### ISSUE THREAD

**Issue by pwichmann** [cytoscape/py2cytoscape#30]
How does this library work?
It could be an amazing library if there was a proper documentation.

What is 'cyjs'? Does that need to imported separately?

**Comment by bdemchak** [comment]
Hi --

Thanks for noticing this library. There is already a fair bit of documentation on this topic. Can you explain what you're trying find?? ... it could be that we need to organize better so that someone with your question could find what they're looking for?? 

Thanks.

**Comment by jorgeboucas** [comment]
Hi @pwichmann, thanks for your interest. You can get some examples on https://github.com/cytoscape/py2cytoscape/tree/develop/examples and soon on py2cytoscape.readthedocs.io
