### ISSUE TITLE
readthedocs

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/py2cytoscape#48]
- basic structure for documentation of new function as one goes along 
- full docs will be added once decision is made on which functions to deprecate

**Comment by jorgeboucas** [comment]
@bdemchak weebhook needed

**Comment by jorgeboucas** [comment]
[py2cytoscape.readthedocs.io](https://py2cytoscape.readthedocs.io) running

@bdemchak - need you user name in https://readthedocs.org to add you as a maintainer.

**Comment by bdemchak** [comment]
Hi, Jorge –

 

My not-so-secret alias is idekerlab.bdemchak@gmail.com <mailto:idekerlab.bdemchak@gmail.com> 

 

Please sign me up …

 

Looking over the document, this looks like a good start, and I think it will be useful almost immediately.

 

The real gold, though, will be in the documentation of the library API. Is that where this is actually going?

**Comment by jorgeboucas** [comment]
done.

Yup, every function will have it's documentation in the docstring and in the readthedocs respective location. In readthedocs there will additionally be an example of `input`, `call`, and `output`.

I will start with the rest functions as I go along building them. Once that is over and we review the whole project I will move on to do the same for all other functions in the package.

For the future, the addition or  modification of functions should only be allowed if the respective documentation in `/docs` has also been changed.

**Comment by bdemchak** [comment]
Nifty!
