### ISSUE TITLE
cybrowser.hide

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/py2cytoscape#52]
window gets hidden but it does not get sent to the results panel as described in the swagger

**Comment by dotasek** [comment]
What endpoint is this? If it's an issue in CyREST, I'll make an issue in the CyREST repo and you can close or link this to it.

**Comment by jorgeboucas** [comment]
sure - I've just tried it on the Command Line Dialog and it doesn't seem to work there as well.

Window goes away but not into the Results panel 

Just mention this issue whenever you open the correct one and I will close it here.

👍

**Comment by dotasek** [comment]
Upon inspection, this is coming from the cybrowser app. I've created an issue there pointing back to this one. 

https://github.com/cytoscape/cyBrowser/issues/2
