### ISSUE TITLE
swagger compliance

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/py2cytoscape#53]
I've created a [compliance table](https://github.com/cytoscape/py2cytoscape/wiki/swagger-compliance)

@AlexanderPico it would be great if you could add the RCy3 part and add new rows as necessary

I guess @dotasek and @bdemchak might want to drop an eye in there as well

**Comment by dotasek** [comment]
I noticed that the string app is included in the Swagger table. It might be wise to limit the scope of py2cytoscape to the Cytoscape API and its Core Apps even in the docs.

**Comment by jorgeboucas** [comment]
that is definitely a good point. 

We should reflect a bit on this:

- A) would we then push towards a self contained packaged (with py2cytoscape as dependency) for every non core app? In this case we can use the String App as a show case.

- B) otherwise we could have it like for core Apps. i.e. `cyrest/string.py` with the respective class and functions inside and then something like a `def string()` in the `cyclient` class in `cyrest/cyrest.py`. Given it would stay fixed to one contained file `cyrest/string.py` and a section in `cyrest/cyrest.py` it would still be easy to both develop and deprecate when required.

For option B it would be important to make sure Apps are enclosed as described for the String App. On the long run B would clearly demand more work from a package maintenance side but also make the package more complete and probably enforce proper and continuous maintenance of all the python interface for non-core apps. 

I would vote for B but I am probably biased as that was my initial intention.

(ps. I added the link to the table which I initially forgot - sorry for that)

**Comment by bdemchak** [comment]
Hi, Jorge –

 

It’s a pretty good topic.

 

If you knew that 40 different apps were to have their own Python and R interfaces, what would you do?

 

We definitely don’t want to be on the hook for creating those interfaces … either the app author or someone who cares about the app will. And they’ll need to be maintained as the app evolves.

 

From the workflow author perspective, it’s counterproductive to make him/her wade through interfaces for a bunch of apps he/she isn’t interested in.

 

So, this argues for the individual modules to be available through appropriate clearinghouses. It’s natural for Python programmers to go to PyPI … and maybe the Cytoscape App store, too. Maybe both.

 

It’s also irritating for a Python programmer to be looking for an app interface and not finding it in short order. That orders for presence in py2cytoscape itself.

 

Given that, we’re looking for a balance. Clearly, interfaces to core apps can be in py2cytoscape. After that, it should be very easy for workflow authors to discover other interfaces.

 

What do you think?? … this is definitely timely.

**Comment by jorgeboucas** [comment]
40 apps at 2 to 40 functions per App feels a bit out of the range to me.

I will give it a try at how String as a separate package would look like before I continue with the rest.

Sounds good?

Do we have a guideline we would like to set for such packages - eg. py2cyString ?

**Comment by dotasek** [comment]
We've already gotten official submissions for about 20 apps, as of the last time Barry spoke to me about it, so I don't think 40 apps is out of range. It's our hope that the number will continue to grow.

I'm all for creating String as a separate package. Diffusion, one of the apps we regularly use as an example, has some python associated with it for test purposes. After taking a look at how String would look as a package we could make this test code more usable as general python.

py2cyWhateverApp sounds fine as a naming guideline.

**Comment by jorgeboucas** [comment]
👍 

- I meant out of range for being centrally maintained inside py2cytoscape

I will go for it then - let me know if there are more Apps in the compliance table that don't belong in "Core Apps"

**Comment by jorgeboucas** [comment]
all swagger calls have been ported since ff2802c
