### ISSUE TITLE
make igraph optional

### ISSUE THREAD

**Issue by schlegelp** [cytoscape/py2cytoscape#56]
Hi. I was wondering if it made sense to make igraph an optional dependency? It can be a pain in the neck to install on some systems and as far as I can tell, it's only relevant for `from_igraph()` in [util_igraph.py](https://github.com/cytoscape/py2cytoscape/blob/1e8f0815869b32b8e62ee558d9b0cddb8be5a720/py2cytoscape/util/util_igraph.py). People might be perfectly happy with using only pure-Python NetworkX. You could wrap the import in a try statement like this:

```python
try:
   import igraph as ig
except Exception as error:   
   print(str(error))
   print("py2cytoscape: Error importing igraph. You won't be able to import from igraph.")
   ig = None
``` 

```python
def from_igraph(igraph_network, layout=None, scale=DEF_SCALING):
   if ig == None:
      raise ImportError('igraph not found')
   ....
```

PS: Love this library. Keep up the good work!

**Comment by AustEcon** [comment]
I'm still having major issues trying to install this igraph dependency on windows 10, python 3.7. 
It really is a pain in the neck... is this supposed to be fixed? / optional in the latest 0.7.1 release on pypi?

**Comment by empet** [comment]
@AustEcon I'm working with igraph for a long time and there is no pain to install it on windows 10 and python 3.7.  Download its wheel (`whl`)  from  Christoph Gohlke's windows binaries, at UC Irvine: https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph
and from cmd install with:
`pip install python_igraph‑0.7.1.post6‑cp37‑cp37m‑win_amd64.whl`

**Comment by AustEcon** [comment]
Oh I'm a dummy... I actually did this and could see it there in my site-packages but wasn't working still... 
The reason: I installed visual studio to compile cairo (another dependency issue of getting py2cytoscape going)... and it made it so that when I type in "py.exe" it returns back the visual studio version now (where none of my pip install commands have any effect...)... Your response gave me the confidence to go back and check it over again! thanks.

**Comment by vtraag** [comment]
Just wanted to give an update on this. We now provide binary wheels of `python-igraph` for all major platforms for all recent Python versions (>= 3.6) on PyPI. We are committed to ensuring `python-igraph` can be installed on Windows simply using `pip`, so if any issues arise, feel free to open an issue in the [`python-igraph`](https://github.com/igraph/python-igraph) repository.

In addition, we also provide `python-igraph` through the `conda-forge` channel in Anaconda.
