### ISSUE TITLE
api(...) method should use raise an exception

### ISSUE THREAD

**Issue by dotasek** [cytoscape/py2cytoscape#57]
I'm looking over the code in base.py and there's a few things I noticed about error handling, particularly linked to the code here: https://github.com/cytoscape/py2cytoscape/blob/61fcae356c611bd9df77011062e34570ec491140/py2cytoscape/cyrest/base.py#L79

There doesn't appear to be an exception thrown when an error condition is encountered. From what I can see, the response for the method is set to the error code.

What I think of when reporting an error is to raise an exception. If a CI Error can be found, it should be parsed and included in the exception:

```python
raise CIError(parsedErrorMessage)
```

I could also be missing some critical information about how this is executed; if this is the case, please let me know where to look.

**Comment by jorgeboucas** [comment]
@dotasek I agree. If I follow the status codes [you pointed out before](http://www.restapitutorial.com/httpstatuscodes.html) will cyrest obey?

More clearly, which codes should give a pass besides 200?

**Comment by jorgeboucas** [comment]
solved in 0.7.0
