### ISSUE TITLE
CyRest in developmental version is not working: <title>Error 405 Method Not Allowed</title>

### ISSUE THREAD

**Issue by IvoLeist** [cytoscape/py2cytoscape#62]
sys.path.insert(0,"/home/user/.local/lib/python2.7/site-packages/py2cytoscape-0.6.2-py2.7.egg/py2cytoscape")
import cyrest as cyrest

# Step 1: Create py2cytoscape client 
cy=cyrest.cyclient()
cy.status()
cy.version()
print cy.commands.list()
cy.commands.namespace("session")
cy.commands.command("session", "new")
cy.session.new()

Output:
CyREST online!
cytoscapeVersion 3.5.1
apiVersion v1
Available namespaces:
  command
  edge
  group
  layout
  network
  node
  session
  table
  view
  vizmap

<Response [405]> 405
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 405 Method Not Allowed</title>
</head>
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /v1/commands/session/new. Reason:
<pre>    Method Not Allowed</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>

**Comment by jorgeboucas** [comment]
@IvoLeist 

could you describe your 

- cytoscape version
- python version
- cyrest version

make sure you have the latest dev version 

```bash
pip uninstall py2cytoscape
pip install git+https://github.com/cytoscape/py2cytoscape.git --user
```

and then

```python
from py2cytoscape import cyrest
cy=cyrest.cyclient()
cy.status()
cy.version()
print cy.commands.list_namespaces()
cy.commands.namespace("session")
cy.commands.command("session", "new")
cy.session.new()
```

**Comment by jorgeboucas** [comment]
deprecated my lack of feedback
