### ISSUE TITLE
Which is active code

### ISSUE THREAD

**Issue by mwang87** [cytoscape/py2cytoscape#66]
There seem to be two libraries in here to use:

https://github.com/cytoscape/py2cytoscape/tree/develop/py2cytoscape/cyrest
https://github.com/cytoscape/py2cytoscape/tree/develop/py2cytoscape/data

Which one is actually active? Seems like cyrest is slightly newer and more featured, but I'm not sure which one to use. 

Thanks!

**Comment by IvoLeist** [comment]
That's a good question: CyRest is the new wrapper so I would suggest to use that one.

However I am glad that the old one is still existing. Somehow I cannot make CyRest work in my project.

*Please ignore my comment, I guess @dotasek provided the correct one.

**Comment by dotasek** [comment]
From a quick look at some of the code, these are both using active code within CyREST. CyREST exposes Cytoscape in two different ways: Functions and Commands. You can read more about these here: https://github.com/cytoscape/cytoscape-automation/wiki/App-Developers:-Adding-Automation-to-Existing-Apps).

The data directory appears to be structured around Functions, while the root directory is based around Commands.

**Comment by mwang87** [comment]
That makes sense. Thanks!

**Comment by jorgeboucas** [comment]
@IvoLeist if you mean #62 please check my reply otherwise do not hesitate to open a new issue.

**Comment by IvoLeist** [comment]
@jorgeboucas sorry for missing the oportunity to help you with issue #62 but I missed your answer.  

As soon as I am in the biolab again (latest in 2 weeks) I can post the issue again by now I found a good work around using the function in /data and Cytoscape.js

Keep up the good work I love py2Cytoscape! :)
