### ISSUE TITLE
Functions code cannot connect to Cytoscape not on default port

### ISSUE THREAD

**Issue by mwang87** [cytoscape/py2cytoscape#67]
I've found if I start up my Cytoscape instance not on port 1234, the code present in this branch can connect to it, but any other commands do not work. 

https://github.com/cytoscape/py2cytoscape/tree/develop/py2cytoscape/data

Specifically this command doesn't work:

cy.style.apply(style=mystyle, network=network1)

It seems that the styles apply is hardcoded with the port.

**Comment by jorgeboucas** [comment]
for this I would recommend moving on to https://github.com/cytoscape/py2cytoscape/tree/develop/py2cytoscape/cyrest - docs on https://py2cytoscape.readthedocs.io/en/latest/

**Comment by jorgeboucas** [comment]
deprecated
