### ISSUE TITLE
Commands code cannot connect to Cytoscape Instance

### ISSUE THREAD

**Issue by mwang87** [cytoscape/py2cytoscape#68]
I've found if I start up my Cytoscape instance the code present in this branch cannot connect to it

https://github.com/cytoscape/py2cytoscape/tree/develop/py2cytoscape/cyrest

**Comment by jorgeboucas** [comment]
could you give us a description of the 
- commands
- cryrest version 
- cytoscape version 
- python version

**Comment by IvoLeist** [comment]
place holder/bookmark for my issue #62 have a similar problem

**Comment by jorgeboucas** [comment]
deprecated
