### ISSUE TITLE
Invalid syntax in util.util_dataframe

### ISSUE THREAD

**Issue by gaberosser** [cytoscape/py2cytoscape#73]
This issue affects me with py2cytoscape 0.7.0.

I installed py2cytoscape using pip in a Python 2.7 virtual environment on a system running Ubuntu 16.04 and Cytoscape 3.6.1.

I've been following the Jupyter tutorial [here](http://nbviewer.jupyter.org/github/idekerlab/py2cytoscape/blob/develop/examples/New_wrapper_api_sample.ipynb). Upon testing a basic import, I received a syntax error:

```
from py2cytoscape.data.cyrest_client import CyRestClient
File "<BLAH>/venv/local/lib/python2.7/site-packages/py2cytoscape/util/util_dataframe.py", line 88
row = (source, itr, target, *extra_values)
```

I'm not certain, but isn't this Python 3 syntax? This is the only file affected. I manually fixed the two affected lines: 88 and 93 in the function `to_dataframe()`. Then everything works fine.

**Comment by jorgeboucas** [comment]
8a55ead should have fixed it
