### ISSUE TITLE
Linking fails when installing through Arch Linux

### ISSUE THREAD

**Issue by moritzschaefer** [cytoscape/py2cytoscape#74]
No Code, No Cytoscape. I just wan to do 

pip install py2cytoscape on Arch Linux. It compiles some time and then exits with an error: 

    /usr/bin/ld: /usr/lib64/libz.a(deflate.o): relocation R_X86_64_PC32 against symbol `deflateResetKeep' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: bad value

Installing through pip with the github link does work.

**Comment by jorgeboucas** [comment]
solution for Arch: "Installing through pip with the github link"

**Comment by moritzschaefer** [comment]
This merely sounds like a solution for a package that is hosted on pypi but thanks for the response
