### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by zachary822** [cytoscape/py2cytoscape#85]
https://github.com/cytoscape/py2cytoscape/blob/41fcca49b842dad78dc0a9fc501e0bc61f6eb4be/py2cytoscape/cyrest/base.py#L24-L29

This is just creating a dict the hard way. If you already know both keys and values, why not just

```python
PARAMS = {'key': 'value'}

PARAMS = set_param(['key'], ['value'])  # this seems so unnecessary
```

Furthermore

```python
def set_param(parameters,values):
     return dict(zip(parameters,values))  # still wholly unncessary, but at least it clearer
```

**Comment by jorgeboucas** [comment]
closed with 0279852 but feel free to clean it for real
