### ISSUE TITLE
Dropping python 2 support?

### ISSUE THREAD

**Issue by zachary822** [cytoscape/py2cytoscape#86]
Some libraries this module depends on, like `networkx` are no longer supporting python 2. Maybe we should consider dropping python 2 support as well?

**Comment by hugovk** [comment]
Python 2 reaches EOL on 2020-01-01.
 
Here's the pip installs for py2cytoscape from PyPI for March 2019, showing low numbers for Python 2.7:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  60.42% |       403 |
| null     |  17.84% |       119 |
|      3.7 |  16.34% |       109 |
|      2.7 |   4.35% |        29 |
|      3.5 |   1.05% |         7 |
| Total    |         |       667 |

Source: `pypistats python_minor py2cytoscape --last-month # pip install pypistats`

**Comment by jorgeboucas** [comment]
agree

**Comment by hugovk** [comment]
Remember to update setup.py:

https://github.com/cytoscape/py2cytoscape/blob/cc326dcd3909ee203b44bed07d63e293f5456d5b/setup.py#L54

Adding `python_requires='>=3.4',` can help pip install the correct version too.
